#!/usr/bin/env bash
# ORCH v0.21.1 smoke test.
#
#   scripts/smoke.sh            # Docker: build, compose up (throw-away project
#                               # + volumes), /healthz, /setup, login, pages, teardown
#   scripts/smoke.sh --local    # no Docker: same checks against serve.py run from
#                               # a clean `git archive` copy (temp state/, SQLite)
#
# Env: SMOKE_PORT (default 5059), SMOKE_PASSWORD, PYTHON (local mode).
#
# v0.21.1: the smoke run is isolated from the deployment's configuration. It
# never loads (or reads) the real .env: Docker mode generates its own env file
# (compose --env-file + ORCH_ENV_FILE), local mode runs a clean `git archive`
# copy with the variables below removed. API keys are blank (model calls are
# mocked) and /setup is exercised with a generated setup token.
set -euo pipefail

MODE=docker
[[ "${1:-}" == "--local" ]] && MODE=local
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PORT="${SMOKE_PORT:-5059}"
BASE="http://127.0.0.1:$PORT"
ADMIN="Smoke Admin"
PASSWORD="${SMOKE_PASSWORD:-Smoke-Test-Pass-$RANDOM-x}"
WORK="$(mktemp -d)"
JAR="$WORK/cookies.txt"
# Own compose project, container, volumes and image tag: never touches a real
# deployment (project "orch" / image orch:0.21.1) running on the same host.
PROJECT="orch-smoke-$$"
SMOKE_IMAGE="orch-smoke:$$"
PID=""
SMOKE_ENV="$WORK/smoke.env"
SMOKE_SETUP_TOKEN="smoke-$(od -An -tx1 -N16 /dev/urandom | tr -d ' \n')"
# Variables a real deployment may set (in .env or the shell) that would change
# what smoke sees: removed from the environment of every smoke process.
ISOLATE_VARS="OPENROUTER_API_KEY OPENROUTER_MODEL OPENROUTER_CHAT_MODEL OPENROUTER_VISION_MODEL
  ORCH_UI_SECRET_KEY ORCH_AUTH_DIR ORCH_STATE_DIR ORCH_SETUP_TOKEN ORCH_SETUP_LOCAL_NO_TOKEN
  ORCH_TRUSTED_HOSTS ORCH_TRUSTED_PROXY ORCH_PROXY_FIX SESSION_COOKIE_SECURE ORCH_CLIENT_NAME
  ORCH_LOGO ORCH_TARGET_MARKET ORCH_BRANDING_FILE ORCH_ENV_FILE ORCH_IMAGE ORCH_PUBLISH_PORT
  COMPOSE_FILE COMPOSE_PROJECT_NAME COMPOSE_PROFILES"
UNSET_ARGS=()
for var in $ISOLATE_VARS; do UNSET_ARGS+=(-u "$var"); done

# Own env file (0600, inside the private temp dir): every setting explicit.
umask 077
cat > "$SMOKE_ENV" <<EOF
# generated by scripts/smoke.sh - throw-away; the real .env is never used
OPENROUTER_API_KEY=
OPENROUTER_MODEL=
OPENROUTER_CHAT_MODEL=
OPENROUTER_VISION_MODEL=
ORCH_DEMO_FORCE_MOCK=1
ORCH_UI_SECRET_KEY=
ORCH_SETUP_TOKEN=$SMOKE_SETUP_TOKEN
ORCH_SETUP_LOCAL_NO_TOKEN=
ORCH_TRUSTED_HOSTS=
ORCH_TRUSTED_PROXY=
ORCH_PROXY_FIX=0
SESSION_COOKIE_SECURE=0
ORCH_CLIENT_NAME=
ORCH_LOGO=
ORCH_TARGET_MARKET=
ORCH_PUBLISH_PORT=$PORT
ORCH_IMAGE=$SMOKE_IMAGE
ORCH_ENV_FILE=$SMOKE_ENV
EOF

compose() {
  (cd "$ROOT" && env "${UNSET_ARGS[@]}" ORCH_ENV_FILE="$SMOKE_ENV" ORCH_PUBLISH_PORT="$PORT" \
     ORCH_IMAGE="$SMOKE_IMAGE" docker compose -p "$PROJECT" --env-file "$SMOKE_ENV" "$@")
}

cleanup() {
  if [[ "$MODE" == docker ]]; then
    compose down -v --remove-orphans >/dev/null 2>&1 || true
    env "${UNSET_ARGS[@]}" docker image rm "$SMOKE_IMAGE" >/dev/null 2>&1 || true
  elif [[ -n "$PID" ]]; then
    kill "$PID" 2>/dev/null || true; wait "$PID" 2>/dev/null || true
  fi
  rm -rf "$WORK"
}
trap cleanup EXIT

fail() { echo "SMOKE FAIL: $*" >&2; [[ -f "$WORK/server.log" ]] && tail -20 "$WORK/server.log" >&2; exit 1; }
csrf() { sed -n 's/.*name="csrf_token" value="\([^"]*\)".*/\1/p' | head -1; }
code() { curl -s -o "$WORK/body" -w '%{http_code}' -b "$JAR" -c "$JAR" "$@"; }

if [[ "$MODE" == docker ]]; then
  command -v docker >/dev/null || fail "docker not found (run with --local to smoke-test without Docker)"
  cd "$ROOT"
  echo "== build + up ($PROJECT, image $SMOKE_IMAGE, port $PORT)"
  compose up -d --build
else
  PY="${PYTHON:-python3}"
  [[ -x "$ROOT/.venv/bin/python" ]] && PY="$ROOT/.venv/bin/python"
  echo "== local: git archive HEAD -> $WORK/app, serve.py on $PORT"
  mkdir -p "$WORK/app"
  git -C "$ROOT" archive HEAD | tar -x -C "$WORK/app"
  [[ ! -e "$WORK/app/.env" ]] || fail "git archive copy must not contain a .env"
  (cd "$WORK/app" && exec env "${UNSET_ARGS[@]}" OPENROUTER_API_KEY= ORCH_PERSIST_SECRET_KEY=1 \
     ORCH_DEMO_FORCE_MOCK=1 ORCH_SETUP_TOKEN="$SMOKE_SETUP_TOKEN" ORCH_PROXY_FIX=0 \
     ORCH_HOST=127.0.0.1 ORCH_PORT="$PORT" \
     "$PY" serve.py >"$WORK/server.log" 2>&1) &
  PID=$!
fi

echo "== wait for /healthz"
for _ in $(seq 1 60); do
  if curl -fsS "$BASE/healthz" -o "$WORK/health" 2>/dev/null; then break; fi
  sleep 2
done
grep -q '"ok": *true' "$WORK/health" 2>/dev/null || fail "/healthz not healthy"
cat "$WORK/health"; echo

echo "== setup mode: every page redirects to /setup"
[[ "$(code "$BASE/")" == 302 ]] || fail "/ should redirect before setup"
[[ "$(code "$BASE/setup")" == 503 ]] || fail "/setup page"
TOKEN="$(csrf < "$WORK/body")"; [[ -n "$TOKEN" ]] || fail "no csrf token on /setup"
grep -q 'name="setup_token"' "$WORK/body" || fail "/setup must ask for the setup token"
[[ "$(code -X POST "$BASE/setup" --data-urlencode "csrf_token=$TOKEN" \
      --data-urlencode "username=$ADMIN" --data-urlencode "password=$PASSWORD" \
      --data-urlencode "password_confirm=$PASSWORD")" == 403 ]] || fail "setup POST without token must be 403"
[[ "$(code "$BASE/setup")" == 503 ]] || fail "/setup page"
TOKEN="$(csrf < "$WORK/body")"
[[ "$(code -X POST "$BASE/setup" --data-urlencode "csrf_token=$TOKEN" \
      --data-urlencode "setup_token=$SMOKE_SETUP_TOKEN" \
      --data-urlencode "username=$ADMIN" --data-urlencode "password=$PASSWORD" \
      --data-urlencode "password_confirm=$PASSWORD")" == 302 ]] || fail "setup POST"
[[ "$(code "$BASE/setup")" == 302 ]] || fail "/setup must close once an account exists"

echo "== login"
[[ "$(code "$BASE/login")" == 200 ]] || fail "/login"
TOKEN="$(csrf < "$WORK/body")"
[[ "$(code -X POST "$BASE/login" --data-urlencode "csrf_token=$TOKEN" \
      --data-urlencode "username=$ADMIN" --data-urlencode "password=$PASSWORD")" == 302 ]] || fail "login POST"

echo "== main pages"
for path in / /tasks /events /chat /inbox /audit /sales /import /admin/users /admin/permissions /admin/permissions.csv; do
  status="$(code "$BASE$path")"
  [[ "$status" == 200 ]] || fail "$path -> $status"
  echo "  $path 200"
done
grep -q "Smoke Admin" "$WORK/body" || fail "permissions export missing the admin"
code "$BASE/" >/dev/null; grep -q 'data-app-version' "$WORK/body" || fail "no version in footer"
echo "SMOKE OK ($MODE)"
